### ISSUE TITLE
第三章-异步IO P63 页 next_tick_set_immediate.js 书中执行结果错误

### ISSUE THREAD

**Issue by YOLO0927** [JacksonTian/diveintonode_examples#16]
####  书中书写的输出结果为

正确执行  
nextTick延迟执行1    
nextTick延迟执行2    
setImmediate延迟执行1   
强势插入  
setImmediate延迟执行2  

####  正确结果应为在macro task setImmediate 队列下的主函数都执行完毕后才调用 micro task 的 process.nextTick 吧

正确执行
nextTick延迟执行1
nextTick延迟执行2
setImmediate延迟执行1
setImmediate延迟执行2
强势插入

#### 附图
[书中图](https://img-blog.csdn.net/2018032518322067?watermark/2/text/aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3lvbG8wOTI3/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70)
[自己的执行结果](https://img-blog.csdn.net/20180325183237356?watermark/2/text/aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3lvbG8wOTI3/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70)

**Comment by JacksonTian** [comment]
书上这个错误是因为在 0.12 还是什么版本的时候，process.nextTick 和 setImmediate 底层更改了实现。因为这个地方的勘误会引起很大篇幅的改动，所以没有做，留到第二版再做把。

**Comment by YOLO0927** [comment]
了解~谢谢朴老师的解答。
