### ISSUE TITLE
188页看不懂

### ISSUE THREAD

**Issue by achillesz** [JacksonTian/diveintonode_examples#17]
朴老师 
突然出现 store.get 
请问 这个 是哪里来的 谢谢

**Comment by JacksonTian** [comment]
store 就是 cache 的抽象。

**Comment by achillesz** [comment]
具体 我咋完成这个demo 啊  是不是先去学redis 之类的

**Comment by JacksonTian** [comment]
看这本书需要有一定的 Node 使用经验。

因为这本书没有把读者当新手，从最基本的讲起来，那样子会有很多篇幅。

**Comment by achillesz** [comment]
嗯 我多了好多年前端。。涉及到数据库 存储 之类的 比较空缺。。

多谢老大
