### ISSUE TITLE
第七章 TLS 客户端的例子

### ISSUE THREAD

**Issue by x-web** [JacksonTian/diveintonode_examples#4]
### 7.5.2 / P173.
```
stream.on('end', function () {
  server.close(); // 这里 server 没有声明
});
```

这里的 server 应该不是服务端的。服务端和客户端应该是分开写的吧，这里监听的 end 事件是为了退出客户端进程（因为我发现这里不写，服务端进程终止，客户端并不退出）。我用 `process.exit(0)` 来退出客户端进程了。

还有按照书里的方法创建好所有的 key 文件，但是由于 openssl 默认不支持自签名的 CA ，所以客户端的代码会报错。
```
{ [Error: self signed certificate] code: 'DEPTH_ZERO_SELF_SIGNED_CERT' }
```

Google解决了：
```
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
var stream = tls.connect(8000, options, function () { /* ... */ } );
```

我的环境：
* Ubuntu 14.04 LTS 32-bit
* node v5.0.0

**Comment by JacksonTian** [comment]
不是默认不支持。版本更新了 需要再看看。新版再修复下。
